    
language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.0
  - 1.1
  - 1.2
notifications:
  email: false

after_success:
  - julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'